### ISSUE TITLE
大佬能否帮看下fritzing生成的gerber 怎么改

### ISSUE THREAD

**Issue by shark526** [acha666/FuckJLC#1]
实在不想重新画一遍， 而且一直觉得很难用就没用起来，目录附上烦请帮忙看看，谢谢。
ale_v6.3_contour.gm1
ale_v6.3_copperBottom.gbl
ale_v6.3_copperTop.gtl
ale_v6.3_drill.txt
ale_v6.3_maskBottom.gbs
ale_v6.3_maskTop.gts
ale_v6.3_pasteMaskTop.gtp
ale_v6.3_pnp.txt
ale_v6.3_silkBottom.gbo
ale_v6.3_silkTop.gto

**Comment by shark526** [comment]
昨晚安readme步骤导出了header， 尝试运行脚本后倒是也没报错， 打zip包之后，用jlcEDA打开没反应，不太懂原理， 望指点，多谢
脚本修改后的目录结构
Gerber_BottomLayer.GBL
Gerber_BottomSilkscreenLayer.GBO
Gerber_BottomSolderMaskLayer.GBS
Gerber_MechanicalLayer1.GM1
Gerber_TopLayer.GTL
Gerber_TopPasteMaskLayer.GTP
Gerber_TopSilkscreenLayer.GTO
Gerber_TopSolderMaskLayer.GTS
grinder_scale_v6.3_drill.txt
grinder_scale_v6.3_pnp.txt

**Comment by acha666** [comment]
`grinder_scale_v6.3_pnp.txt` 是什么文件？
照此修改后应该已经可以正常打板

**Comment by shark526** [comment]
你好， 以下是文件grinder_scale_v6.3_pnp.txt内容
应该是敷铜文件。
生成的这些文件我打成zip包， lcEDA里点打开后没任何反应，也不报错。

这两个txt文件需要在里面吗？还有就是文件名是不是要修改一下？

另外我看代码最后把 header（G04 Layer: **TopLayer**....）写入到每个文件里了， 这里header 内容不需要区分么？只要topLayer的就可以了？



*Pick And Place List
*Company=
*Author=
*eMail=
*
*Project=grinder_scale_v6.3
*Date=00:03:23
*CreatedBy=Fritzing 0.9.5d.2020-02-07.CD-548-0-3d61c58
*
*
*Coordinates in mm, always center of component
*Origin 0/0=Lower left corner of PCB
*Rotation in degree (0-360, math. pos.)
*
*No;Value;Package;X;Y;Rotation;Side;Name
1;;THT;61.1052;-31.5272;180;Bottom;D7
2;;THT;8.03517;-13.7471;-90;Bottom;L
3;;;59.8679;-21.3438;0;Bottom;Copper Fill30
4;;THT;14.1152;-78.5172;180;Bottom;L1
5;;;15.0368;-21.5724;0;Bottom;Copper Fill25
6;;THT;50.9452;-5.08735;0;Bottom;J5
7;;THT;63.6452;-11.2072;90;Bottom;Encoder:V-D7D6D5-G
8;;;5.48945;-13.4121;0;Bottom;Hole8
9;;;5.48945;-14.6821;0;Bottom;Hole6
10;;THT;75.0752;-59.4672;180;Bottom;D0
11;;THT;37.9401;-36.6072;-90;Bottom;!
12;;;21.6187;-14.3488;0;Bottom;Hole3
13;;THT;46.5002;-9.93723;90;Bottom;GND
14;;THT;63.6452;-62.0072;180;Bottom;D6
15;;;50.5395;-55.8661;-90;Bottom;TXT1
16;;THT;5.22517;-83.5972;-90;Bottom;!
17;;;14.859;-26.4492;0;Bottom;Copper Fill22
18;;THT;3.05017;-13.7471;-90;Bottom;N
19;;;21.6187;-12.6919;0;Bottom;Hole4
20;;;38.6334;-45.0166;0;Bottom;Copper Fill40
21;;;72.1902;-53.1669;-90;Bottom;TXT1
22;;THT;66.1852;-59.4672;180;Bottom;D5
23;;THT;46.5002;-7.39723;90;Bottom;VCC
24;;;63.8049;-4.3766;0;Bottom;Copper Fill17
25;;THT;63.6452;-31.5272;180;Bottom;D6
26;;;27.3812;-24.5188;0;Bottom;Copper Fill38
27;;;5.48945;-14.0471;0;Bottom;Hole7
28;;THT;58.5652;-31.5272;180;Bottom;3V
29;;THT;26.8152;-26.4472;-90;Bottom;OLED:D2-D1-3v-G
30;;THT;40.7852;-23.9072;-180;Bottom;J16
31;;THT;27.4502;-9.93723;0;Bottom;NC
32;;THT;14.1152;-83.5972;180;Bottom;N1
33;;;31.5669;-73.3141;0;Top;IMG1
34;;;21.6187;-13.0788;0;Bottom;Hole2
35;;THT;20.4652;-50.5772;180;Bottom;J17
36;;;38.6334;-45.0166;0;Bottom;Copper Fill36
37;;THT;16.6552;-64.5472;90;Bottom;HX711-G-D3-D4-V
38;;;52.643;-84.3476;0;Top;TXT2
39;;THT;66.1852;-31.5272;-90;Bottom;D5
40;;THT;7.76517;-20.0972;-90;Bottom;fuse
41;;;5.48945;-12.7771;0;Bottom;Hole9
42;;;44.8818;-44.5086;0;Bottom;Copper Fill35
43;;THT;23.3706;-13.7391;-90;Bottom;-
44;;;63.8049;-4.3766;0;Bottom;Copper Fill9
45;;THT;47.1352;-59.4672;180;Bottom;A0
46;;THT;8.40017;-32.7972;90;Bottom;L
47;;;45.212;-65.8446;0;Bottom;Copper Fill26
48;;THT;33.1652;-84.8672;-90;Bottom;!2
49;;;51.7398;-35.3392;0;Bottom;Copper Fill39
50;;;47.0917;-16.0098;0;Bottom;Copper Fill34
51;;;54.483;-26.5762;0;Bottom;Copper Fill37
52;;THT;46.5002;-12.4772;90;Bottom;T1
53;;;64.9225;-21.3438;0;Bottom;Copper Fill32
54;;THT;64.4551;-8.66714;-90;Bottom;J6
55;;THT;46.5002;-4.85723;90;Bottom;RGND
56;;THT;25.5452;-84.8672;-90;Bottom;!1
57;;;21.6187;-14.6889;0;Bottom;Hole1
58;;THT;13.4802;-32.7972;90;Bottom;COM
59;;sot23-5;44.6254;-18.8668;90;Top;C045
60;;THT;3.32017;-32.7972;90;Bottom;N
61;;THT;14.1152;-73.4372;180;Bottom;COM1
62;;THT;72.5352;-83.5972;-90;Bottom;!
63;;;21.6187;-13.667;0;Bottom;Hole5
64;;THT;19.8797;-13.7473;-90;Bottom;5V+
65;;THT;16.0202;-25.1772;0;Bottom;relay
66;;THT;61.1052;-64.5472;180;Bottom;D7
67;;THT;37.9401;-44.2272;-90;Bottom;!
68;;;62.3825;-21.3438;0;Bottom;Copper Fill31
69;;;14.859;-23.9092;0;Bottom;Copper Fill24

**Comment by shark526** [comment]
我在想我可能理解错你的意思了， 你这个脚本是为了把gerber文件修改为下单助手能通过的格式， 并不是为了能在lcEDA里能编辑，是这样的么？

**Comment by acha666** [comment]
是的...立创EDA据我所知不能直接编辑gerber。最近嘉立创免费打样规则有更改，只有立创EDA的文件才能免费。这个脚本的目的在于此

**Comment by shark526** [comment]
> 

好的，多谢大佬， 我这就去试试

**Comment by shark526** [comment]
果然提交成功了， 感谢感谢！
