### ISSUE TITLE
遇到操作上的问题，希望能解答

### ISSUE THREAD

**Issue by winwin163** [acha666/FuckJLC#2]
header获取方法：立创EDA导出gerber→随意打开一个gerber文件。请问具体如何导出呢？操作方法是什么？还有path那里gerber_PCB1应该用打包好的压缩包还是PCBdoc？

**Comment by acha666** [comment]
Q1: 以文本形式随意打开gerber中的某一层
Q2: 显然是解压后的gerber，注意目录应使用正斜杠`/`或将反斜杠转义
此外目前不替换Header也能正常使用

**Comment by winwin163** [comment]
解决了，谢谢大佬！
