### ISSUE TITLE
请问这个要怎么使用啊

### ISSUE THREAD

**Issue by thinker-niu** [acha666/FuckJLC#5]

**Comment by acha666** [comment]
不怎么使用
脚本主要提供一个思路，即修改文件名格式以及文件头，不保证脚本好用




------------------&nbsp;Original&nbsp;------------------
From:                                                                                                                        "acha666/FuckJLC"                                                                                    ***@***.***&gt;;
Date:&nbsp;Tue, Sep 20, 2022 02:04 PM
***@***.***&gt;;
***@***.***&gt;;
Subject:&nbsp;[acha666/FuckJLC] 请问这个要怎么使用啊 (Issue #5)

**Comment by thinker-niu** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by thinker-niu** [comment]
好的，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "acha666/FuckJLC"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月20日(星期二) 下午2:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [acha666/FuckJLC] 请问这个要怎么使用啊 (Issue #5)





 不怎么使用 
 脚本主要提供一个思路，即修改文件名格式以及文件头，不保证脚本好用 
 
 
 
 
 ------------------&amp;nbsp;Original&amp;nbsp;------------------ 
 From:                                                                                                                        "acha666/FuckJLC"                                                                                    ***@***.***&amp;gt;; 
 Date:&amp;nbsp;Tue, Sep 20, 2022 02:04 PM 
 ***@***.***&amp;gt;; 
 ***@***.***&amp;gt;; 
 Subject:&amp;nbsp;[acha666/FuckJLC] 请问这个要怎么使用啊 (Issue #5)
