### ISSUE TITLE
请问modify.py 还能正常使用嘛？

### ISSUE THREAD

**Issue by MrSToneX** [acha666/FuckJLC#6]

**Comment by acha666** [comment]
可以，写的比较烂可能会报错，仅是提供一个思路




------------------&nbsp;Original&nbsp;------------------
From:                                                                                                                        "acha666/FuckJLC"                                                                                    ***@***.***&gt;;
Date:&nbsp;Mon, Sep 26, 2022 10:51 AM
***@***.***&gt;;
***@***.***&gt;;
Subject:&nbsp;[acha666/FuckJLC] 请问modify.py 还能正常使用嘛？ (Issue #6)

**Comment by MrSToneX** [comment]
KiCAD导出的全都是.gbr和.drl，哈哈， 不太懂代码，打开看了下代码貌似是根据.gbl .gko等文件格式进行重命名的，另外貌似EDA的gerber里的代码结构也和kicad导出的不一样，难道是eda更新了

**Comment by acha666** [comment]
https://github.com/acha666/FuckJLC/blob/95ecb1a2c236438ca9d703deba82fd45d81c979a/README.md?plain=1#L26
